### ISSUE TITLE
pipeline_test.sh results different than readme

### ISSUE THREAD

**Issue by AndrewDDavis** [pnlbwh/dMRIharmonization#7]
I ran the `pipeline_test.sh`, and it did indeed finish in an hour with 16 cores and 8 GB of RAM. The readme says the result should have been this:

> CONNECTOM mean FA:  0.675917931134666
> PRISMA mean FA before harmonization:  0.8008729791383536
> PRISMA mean FA after harmonization:  0.6366103024088171

However, my result values were different:

> CONNECTOM mean FA:  0.6432159691396834
> PRISMA mean FA before harmonization:  0.7096586917137321
> PRISMA mean FA after harmonization:  0.6152543085182999 

Is this difference expected?

**Comment by tashrifbillah** [comment]
The discrepancy can be attributed to non deterministic registration by ANTs. I wouldn't be worried about this since meanFA changed in the right direction and came closer to that of reference site.

ITKv5 and ANTs 2.3.0 allows deterministic registration. Utilizing that, we shall come up with concrete numbers on a future release.

**Comment by AndrewDDavis** [comment]
OK, that's good to hear -- thanks for the explanataion.
