### ISSUE TITLE
Applying the harmonization to other diffusion weighted images

### ISSUE THREAD

**Issue by JoaoPaulo100** [pnlbwh/dMRIharmonization#73]
Dear Experts,

Thanks for developing such a great tool. We were wondering if this approach could also be used for different maps (Axial diffusivity, Radial diffusivity, etc). I saw FA, MD, and GFA here and in the paper. Is there a way to also get these other maps harmonized? 

Thanks!
João

**Comment by suheyla2** [comment]
Dear Joao,

Our harmonization method is directly applied to the diffusion MRI data itself. Any model fitting can be applied after harmonization.
After harmonizing diffusion MRI data, you can create any maps you want.

I hope this helps.

Best,
Suheyla

On 9 Mar 2021, at 17:46, JoaoPaulo100 ***@***.***> wrote:

﻿

        External Email - Use Caution

Dear Experts,

Thanks for developing such a great tool. We were wondering if this approach could also be used for different maps (Axial diffusivity, Radial diffusivity, etc). I saw FA, MD, and GFA here and in the paper. Is there a way to also get these other maps harmonized?

Thanks!
João

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1F6VG5rckWReD1uduYD-QqS2nOxjWAcus1VRkLcFqk_-O893puCqWXoLajKOvmZBlzAwc4cBT6WYkP8Ajhv9g3hemrJX15QvUTbzs1Y4D2pA5fN3ZboHKX7f0q6-Wd9Fz_LcVMzW3Tk9pRW9XNjUX8Is3PsK6ZySM6Tev8F89RDNFwDnE4PmvDvtds0s7SrzGctgSuv5EdJc47U4otE4JJ-2_UQqQ2DmdeF5mnjy11QhdlX1u4zh9J1X7qdE3Rzv03Xh7UUK1DHUNWiKGMRbLQg/https%3A%2F%2Fgithub.com%2Fpnlbwh%2FdMRIharmonization%2Fissues%2F73>, or unsubscribe<https://secure-web.cisco.com/1WhdqrDA3zldqAHVRjnF-E6HEfIB4Y0wH_ZEf4tUZ-bKab3epjEfFK3Q3tRA0iEUoD3Wqz9CEORwhGENBcSazhxZpME56E3TBv_BigGIPABPW2YvY5VRUNkCSns7G0xAhnYIm-rbMJvOvAGVVoWYdiRzyEWY-HHHODbvTiNyxh6Iwnhvt59V8u74iuuNV3fCj9z5vjn21Xun9TEpp8_E5GuEiytDmilDz8nuOm1oecSxmEMT38HnAOd5D21taR-kOY3_CBojmWv_H0vJ4Xcqz5g/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGLM7TH5TIPGAYPFA5IS5QTTC2JJHANCNFSM4Y4UL7XQ>.
The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at http://www.massgeneralbrigham.org/complianceline . If the e-mail was sent to you in error but does not contain patient information, please contact the sender and properly dispose of the e-mail.
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by JoaoPaulo100** [comment]
Dear Suheyla,

Thank you so much for your response! I probably missed something in the instructions. 

In the test data provided, and using the 'C" participant as reference, this would be the harmonized dMRI image, correct?  /dMRIharmonization/lib/tests/connectom_prisma/prisma/C/harmonized_dwi_C_prisma_st_b1200_bmapped_resampled.nii.gz

Thanks!
João Paulo

**Comment by suheyla2** [comment]
Yes, it is the harmonized dMRI data.

Best,
Suheyla

On 9 Mar 2021, at 18:56, JoaoPaulo100 ***@***.***> wrote:

﻿

        External Email - Use Caution

Dear Suheyla,

Thank you so much for your response! I probably missed something in the instructions.

In the test data provided, and using the 'C" participant as reference, this would be the harmonized dMRI image, correct? /dMRIharmonization/lib/tests/connectom_prisma/prisma/C/harmonized_dwi_C_prisma_st_b1200_bmapped_resampled.nii.gz

Thanks!
João Paulo

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1lY9eco-trCyZ6WsMPC3_ayD3Kcs-H2DMB-Tz39Yr1HTCXTtZr8PS6Y2sQUbF9Jnzi9eo_YYO2ifBjUj6CDqFNnxqvpv9Mbvictk7e7UTtjeBENW6EuwcVTh8pwxiR_WQLhtqrEBJRwX6ZpiSzgc39yOURSvj6YGGYQfzfG5Ii_Bgxw_4HT7JE735DNvdPJSTXPCicG7WCfKjjdCj_EqoMjX19YNsgfqygNc3ISPJpGnCRI4WnuWlxfEWxLdW7HFa/https%3A%2F%2Fgithub.com%2Fpnlbwh%2FdMRIharmonization%2Fissues%2F73%23issuecomment-794625160>, or unsubscribe<https://secure-web.cisco.com/1_xpLJEjC0kBt9gzdJNggOHRX0cpAjAvahEExFcpX5FxTapeh1DoRrulH3CK8RlPwvjgu7lvg9pVx9Mj5o2jC2Zld54gYgQ6snfVrI56uJXbOzilMh-Y0MzQWF9-XZjfg8d4G4Agzw1qItRkThiPPc1GX1VNmrGaW399jRo8iAu_d3ZN4OAO4jKo3YQii3jzyz8Zw80kR1NQJTtKoTnLUUg_-F4usoDVfJ7abIXZ9DPeS9Uv51N0oRkwLOBkIxMJ8/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGLM7TE6G4WAVAM7EGWYAJTTC2RPZANCNFSM4Y4UL7XQ>.
The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at http://www.massgeneralbrigham.org/complianceline . If the e-mail was sent to you in error but does not contain patient information, please contact the sender and properly dispose of the e-mail.
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by JoaoPaulo100** [comment]
Thanks!

**Comment by JoaoPaulo100** [comment]
No, they don't. However, I'll check all the inputs again.

Thank you so much for linking the comment! I'll look into this.

**Comment by tashrifbillah** [comment]
Hi @JoaoPaulo100 , closing this for now. Feel free to reopen if needed.
