### ISSUE TITLE
Skipping unring step

### ISSUE THREAD

**Issue by josephmje** [pnlbwh/dMRIharmonization#74]
Hi all,

I noticed that the pipeline performs Gibbs unringing. If this step is already part of a pre-processing workflow, should it be skipped when running harmonization?

Thank you!

**Comment by suheyla2** [comment]
Hi,

Are you using the --resample flag in the harmonization?
Gibbs unringing is only applied with --resample.

Best,
Suheyla


________________________________
From: Michael Joseph ***@***.***>
Sent: Wednesday, March 10, 2021 12:47 PM
To: pnlbwh/dMRIharmonization ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pnlbwh/dMRIharmonization] Skipping unring step (#74)


        External Email - Use Caution

Hi all,

I noticed that the pipeline performs Gibbs unringing. If this step is already part of a pre-processing workflow, should it be skipped when running harmonization?

Thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1GHfRT9_qa3uznVgpnsqrhcKs-AqglXD60yMbAbWBt1A5iy2kwi_YHE9htNCJZewkUEOgbFbtTkpwDNIr0ouftj7Jlhxm3pvzJOc0mj_FCzU-LqAZB2BQwXsljGejooLikOoXI-Iy8Bm-5j_cpzgeQF0PW6f13zjH_ACVtWTcml7Gl-J70lNtPu5f2JwDKkHAro-X2TCFCydnNPAwI6iA-Hp5SXoXuq9qRnBypMdvKjg2rmkxUy3xaAuMqh9OZUt6/https%3A%2F%2Fgithub.com%2Fpnlbwh%2FdMRIharmonization%2Fissues%2F74>, or unsubscribe<https://secure-web.cisco.com/1H5kSN7U3rtXbCeyIMc-Ey58EFxf7w4De5Q8nXy2NDjAnR1iubDVaEye9A1jGqxSFa83jH9FMQ9kIUXXhXzeR0sRf42p8OSG1mx3HKwm_YpnW6xzEvQtveMvqbaaDaM5pPj2JVbjxcBQUX1gzt9KWrg209VAqb1ZAatk741iTqqxd7YRoaX0VWzNW8mHKijGIggWXmTT1crURAYrLcl8muFuo5cCU0SDlytNm0c-VkueNhPher7A4pybSu68-2ayL/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGLM7TB522F3FZFIT366MXTTC6PB5ANCNFSM4Y6RFUFQ>.
The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at http://www.massgeneralbrigham.org/complianceline . If the e-mail was sent to you in error but does not contain patient information, please contact the sender and properly dispose of the e-mail.
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by josephmje** [comment]
Thank you @suheyla2! I didn't realize that unringing only runs when the flag is used.
